server:
  port: 8082
spring:
  application:
    name: eureka-employee-work-time
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
          brokers: localhost:9092
          configuration:
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
            num.partitions: 4  # Установка количества партиций
      bindings:
        checkEmployeeEventProcessor-in-0:
          destination: create-employee
        checkEmployeeEventProcessor-out-0:
          destination: salary-employee
  data:
    mongodb:
      host: localhost
      port: 27017
      database: workday
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
